"""test  migration

Revision ID: d28a8c909b7f
Revises: 01a00debf841
Create Date: 2024-04-09 11:30:14.186061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28a8c909b7f'
down_revision = '01a00debf841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('borough', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parks'))
    )
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_fields_park_id_parks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fields'))
    )
    op.create_table('permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_permits_field_id_fields')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_permits_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permits'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permits')
    op.drop_table('fields')
    op.drop_table('parks')
    # ### end Alembic commands ###
